export const homeObjOne = {
	id: 'about',
	lightBg: false,
	lightText: true,
	lightTextDesc: true,
	topLine: 'Premium Bank',
	headline: 'Unlimited Transactions with zero fees',
	description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charger any fees',
	buttonLabel: 'Getting Started',
	imgStart: true,
	img: require('../../images/svg-1.svg'),
	alt: 'Car',
	dark: true,
	primary: true,
	darkText: false,
};

export const homeObjTwo = {
	id: 'discover',
	lightBg: true,
	lightText: false,
	lightTextDesc: true,
	topLine: 'Unlimited Access',
	headline: 'Login to your account at any time',
	description: 'We have you covered no matter where are you located. All you need is an internet connection or a phone or computer',
	buttonLabel: 'Learn More',
	imgStart: false,
	img: require('../../images/svg-5.svg'),
	alt: 'Piggy Bank',
	dark: false,
	primary: false,
	darkText: true,
};

export const homeObjThree = {
	id: 'signup',
	lightBg: true,
	lightText: false,
	lightTextDesc: true,
	topLine: 'Join our Team',
	headline: 'Creating an account is extremely easy',
	description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charger any fees',
	buttonLabel: 'Start Now',
	imgStart: true,
	img: require('../../images/svg-6.svg'),
	alt: 'Paper',
	dark: false,
	primary: false,
	darkText: true,
};
